### ISSUE TITLE
Bugs out when changes states.

### ISSUE THREAD

**Issue by bboychris168** [isaacKenyon/VALORANT-rank-yoinker#7]
The application crashes when it goes from menu to in game updates.

```Fetching Players [########################################] 1/1 [100%] in 0.3s (3.12/s)
+-------------------------------------------------------------------------------------------+
|                                 Valorant status: In-Menus                                 |
+-------+-------+---------------+-----------+----+-----------+----------------------+-------+
| Party | Agent |      Name     |    Rank   | RR | Peek rank | Leaderboard Position | Level |
+-------+-------+---------------+-----------+----+-----------+----------------------+-------+
|   ■   |       | bboychris#OCE | Diamond 2 | 38 | Diamond 3 |          0           |   82  |
+-------+-------+---------------+-----------+----+-----------+----------------------+-------+
Fetching Players [#####################################!  ] (!) 13/14 [93%] in 2.5s (5.23/s)
Traceback (most recent call last):
  File "c:\Users\BBOYCHRIS\Desktop\CODING\VALORANT-rank-yoinker\main.py", line 522, in <module>
    rank = getRank(player["Subject"], seasonID)
  File "c:\Users\BBOYCHRIS\Desktop\CODING\VALORANT-rank-yoinker\main.py", line 306, in getRank
    for season in r["QueueSkills"]["competitive"]["SeasonalInfoBySeasonID"]:
TypeError: 'NoneType' object is not iterable
PS C:\Users\BBOYCHRIS\Desktop\CODING\VALORANT-rank-yoinker> ```

**Comment by OwOHamper** [comment]
Which version did you use?

**Comment by bboychris168** [comment]
I pulled your latest commit.

**Comment by isaacKenyon** [comment]
This error happens when you queue with someone who has yet to play comp, should happen infrequently enough to not matter too much.

**Comment by bboychris168** [comment]
Ok I was in deathmatch and it was happening alot.

**Comment by isaacKenyon** [comment]
If it was happening all throughout that deathmatch then chances are it was the same player causing, it because how would it get fixed :P

Gonna be looked into

**Comment by bboychris168** [comment]
Ok sounds good, please look into it. The app is very usefull.

**Comment by OwOHamper** [comment]
Alright thank you for the report, currently im finding someone who hasn't played comp (shouldn't be that hard) and debug from there. 
PS: You are prob playing low rank deathmatches that's why it's happening so often.

**Comment by isaacKenyon** [comment]
^^ join the discord to receive your bug hunter prize

**Comment by bboychris168** [comment]
Maybe you should grab someones smurf account and test it that way.

**Comment by isaacKenyon** [comment]
Should be fixed with new release.
