### ISSUE TITLE
The program has encountered an error. If the problem persists, please reach support with the logs found in C:\Users\ALT-PC-1\Desktop\VALORANT-rank-yoinker-2.0\build\exe.win-amd64-3.10\logs press enter to exit...

### ISSUE THREAD

**Issue by WhosOn** [isaacKenyon/VALORANT-rank-yoinker#83]
[2022.06.30-12.46.22] got region from logs '['na', ['na-1', 'na']]'
[2022.06.30-12.46.22] Api urls: pd_url: 'https://pd.na.a.pvp.net', glz_url: 'https://glz-na-1.na.a.pvp.net'
[2022.06.30-12.46.22] opened lockfile
[2022.06.30-12.46.22] got version from logs 'release-05.00-shipping-6-725355'
[2022.06.30-12.46.22] Traceback (most recent call last):
  File "main.py", line 49, in <module>
  File "C:\Users\ALT-PC-1\Desktop\VALORANT-rank-yoinker-2.0\src\requests.py", line 33, in check_version
    if not rStatus["status_ok"] or rStatus["print_message"]:
KeyError: 'status_ok'

**Comment by D3CRYPT360** [comment]
please update to the latest version 2.0
