### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by WhosOn** [isaacKenyon/VALORANT-rank-yoinker#86]
[2022.07.03-21.16.21] got region from logs '['na', ['na-1', 'na']]'
[2022.07.03-21.16.21] Api urls: pd_url: 'https://pd.na.a.pvp.net', glz_url: 'https://glz-na-1.na.a.pvp.net'
[2022.07.03-21.16.21] opened lockfile
[2022.07.03-21.16.21] got version from logs 'release-05.00-shipping-11-729462'
[2022.07.03-21.16.21] Traceback (most recent call last):
  File "main.py", line 49, in <module>
  File "D:\Tools\Val Rank Tool Source\Val Rank Tool Source\src\requests.py", line 33, in check_version
    if not rStatus["status_ok"] or rStatus["print_message"]:
KeyError: 'status_ok'

**Comment by WhosOn** [comment]
i did download the 2.0 source code

**Comment by D3CRYPT360** [comment]
Are you sure? because that specific error will only occur on versions below 2.0
