### ISSUE TITLE
Web socket issue?

### ISSUE THREAD

**Issue by WhosOn** [isaacKenyon/VALORANT-rank-yoinker#90]
[2022.07.11-02.32.30] got region from logs '['na', ['na-1', 'na']]'
[2022.07.11-02.32.30] Api urls: pd_url: 'https://pd.na.a.pvp.net', glz_url: 'https://glz-na-1.na.a.pvp.net'
[2022.07.11-02.32.30] opened lockfile
[2022.07.11-02.32.30] got version from logs 'release-05.00-shipping-11-729462'
[2022.07.11-02.32.31] config.json not found, creating new one
[2022.07.11-02.32.31] color config prompt called
[2022.07.11-02.32.31] config opened
[2022.07.11-02.32.35] User inputted Vandal as the weapon
[2022.07.11-02.32.35] Vandal weapon has been added to the config file by user
[2022.07.11-02.32.35] got cooldown with value '10'
[2022.07.11-02.32.36] retrieved agent dict: {None: None, '': '', 'dade69b4-4f5a-8528-247b-219e5a1facd6': 'Fade', '5f8d3a7f-467b-97f3-062c-13acf203c006': 'Breach', 'f94c3b30-42be-e959-889c-5aa313dba261': 'Raze', '22697a3d-45bf-8dd7-4fec-84a9e28c69d7': 'Chamber', '601dbbe7-43ce-be57-2a40-4abd24953621': 'KAY/O', '6f2a04ca-43e0-be17-7f36-b3908627744d': 'Skye', '117ed9e3-49f3-6512-3ccf-0cada7e3823b': 'Cypher', '320b2a48-4d9b-a075-30f1-1f93a9b638fa': 'Sova', '1e58de9c-4950-5125-93e9-a0aee9f98746': 'Killjoy', '707eab51-4836-f488-046a-cda6bf494859': 'Viper', 'eb93336a-449b-9c1b-0a54-a891f7921d69': 'Phoenix', '41fb69c1-4189-7b37-f117-bcaf1e96f1bf': 'Astra', '9f0d8ba9-4140-b941-57d3-a7ad57c6b417': 'Brimstone', 'bb2a4828-46eb-8cd1-e765-15848195d751': 'Neon', '7f94d92c-4234-0a36-9646-3a87eb8b5c89': 'Yoru', '569fdd95-4d10-43ab-ca70-79becc718b46': 'Sage', 'a3bfb853-43b2-7238-a4f1-ad90e9e46bcc': 'Reyna', '8e253930-4c05-31dd-1b6c-968525494517': 'Omen', 'add6443a-41bd-e414-f6ad-e58d267f4e95': 'Jett'}
[2022.07.11-02.32.36] retrieved map dict: {None: None, '/game/maps/ascent/ascent': 'Ascent', '/game/maps/bonsai/bonsai': 'Split', '/game/maps/canyon/canyon': 'Fracture', '/game/maps/duality/duality': 'Bind', '/game/maps/foxtrot/foxtrot': 'Breeze', '/game/maps/pitt/pitt': 'Pearl', '/game/maps/port/port': 'Icebox', '/game/maps/poveglia/range': 'The Range', '/game/maps/triad/triad': 'Haven'}
[2022.07.11-02.32.36] VALORANT rank yoinker v2.0
[2022.07.11-02.32.36] got version from logs 'release-05.00-shipping-11-729462'
[2022.07.11-02.32.36] fetch: url: 'custom', endpoint: https://shared.na.a.pvp.net/content-service/v3/content, method: get, response code: 200
[2022.07.11-02.32.36] retrieved season id: 67e373c7-48f7-b422-641b-079ace30b427
[2022.07.11-02.32.38] getting new MENUS scoreboard
[2022.07.11-02.32.38] retrieved party members: [{'Subject': '8cf4f951-f7ad-5e5f-b9ac-71a7e2be0a3b', 'PlayerIdentity': {'AccountLevel': 32}}]
[2022.07.11-02.32.38] got version from logs 'release-05.00-shipping-11-729462'
[2022.07.11-02.32.38] got version from logs 'release-05.00-shipping-11-729462'
[2022.07.11-02.32.38] fetch: url: 'pd', endpoint: /mmr/v1/players/8cf4f951-f7ad-5e5f-b9ac-71a7e2be0a3b, method: get, response code: 200
[2022.07.11-02.32.38] retrieved rank successfully
[2022.07.11-02.32.38] Traceback (most recent call last):
  File "main.py", line 130, in <module>
  File "C:\Users\ALT-PC-1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\ALT-PC-1\Desktop\VALORANT-rank-yoinker-main\VALORANT-rank-yoinker-main\src\websocket.py", line 40, in recconect_to_websocket
    self.websocket_client = websockets.connect(url, ssl=self.ssl_context, extra_headers=local_headers)
  File "C:\Users\ALT-PC-1\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\imports.py", line 77, in __getattr__
    return import_name(name, source, namespace)
  File "C:\Users\ALT-PC-1\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\imports.py", line 27, in import_name
    module = __import__(source[level:], namespace, None, [name], level)
ModuleNotFoundError: No module named 'websockets.legacy.client'

**Comment by OwOHamper** [comment]
yep forgot updating requirements.txt, gonna update later today

**Comment by OwOHamper** [comment]
should be fixed in latest commit
